#!/usr/bin/env python3
"""
CSV -> puzzles.dart converter for Hayem (Connections-style game)

Usage:
    python3 csv_to_dart.py puzzles_full.csv > puzzles.dart

Expects CSV columns: puzzle_number, category_name, category_hint, word, difficulty
Each puzzle must have exactly 4 categories x 4 words = 16 rows.
"""

import csv
import sys
from collections import defaultdict, OrderedDict

# Color palette — cycles through 4 slots per puzzle (purple, teal, amber, coral)
COLOR_SLOTS = [
    {
        "color": "_purpleLight", "textColor": "_purple",
        "borderColor": "_purpleBorder", "emoji": "🟪",
    },
    {
        "color": "_tealLight", "textColor": "_teal",
        "borderColor": "_tealBorder", "emoji": "🟩",
    },
    {
        "color": "_amberLight", "textColor": "_amber",
        "borderColor": "_amberBorder", "emoji": "🟨",
    },
    {
        "color": "_coralLight", "textColor": "_coral",
        "borderColor": "_coralBorder", "emoji": "🟧",
    },
]

HEADER = '''// lib/data/puzzles.dart
// AUTO-GENERATED by csv_to_dart.py — do not edit by hand.
// To update content, edit the CSV and re-run the script.

import 'package:flutter/material.dart';
import '../models/category.dart';

const Color _purple = Color(0xFF3C3489);
const Color _purpleLight = Color(0xFFEEEDFE);
const Color _purpleBorder = Color(0xFFAFA9EC);
const Color _teal = Color(0xFF085041);
const Color _tealLight = Color(0xFFE1F5EE);
const Color _tealBorder = Color(0xFF5DCAA5);
const Color _amber = Color(0xFF633806);
const Color _amberLight = Color(0xFFFAEEDA);
const Color _amberBorder = Color(0xFFEF9F27);
const Color _coral = Color(0xFF712B13);
const Color _coralLight = Color(0xFFFAECE7);
const Color _coralBorder = Color(0xFFF0997B);

'''

FOOTER = '''
Puzzle getTodayPuzzle() {
  final today = DateTime.now();
  final startDate = DateTime(2025, 1, 6); // Day 1 launch date
  final daysSinceStart = today.difference(startDate).inDays;
  final puzzleIndex = daysSinceStart % allPuzzles.length;
  return allPuzzles[puzzleIndex < 0 ? 0 : puzzleIndex];
}

Puzzle getPuzzleByNumber(int number) {
  return allPuzzles.firstWhere(
    (p) => p.number == number,
    orElse: () => allPuzzles.first,
  );
}
'''


def esc(s: str) -> str:
    """Escape a string for Dart single-quoted literal."""
    return s.replace("\\", "\\\\").replace("'", "\\'")


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 csv_to_dart.py <input.csv> [output.dart]", file=sys.stderr)
        sys.exit(1)

    csv_path = sys.argv[1]
    out_path = sys.argv[2] if len(sys.argv) > 2 else None

    with open(csv_path, encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    # Group rows by puzzle_number -> category_name (preserve order of first appearance)
    puzzles = OrderedDict()
    for row in rows:
        pn = int(row["puzzle_number"])
        cat = row["category_name"]
        puzzles.setdefault(pn, OrderedDict())
        puzzles[pn].setdefault(cat, {
            "hint": row["category_hint"],
            "words": [],
            "difficulties": [],
        })
        puzzles[pn][cat]["words"].append(row["word"])
        puzzles[pn][cat]["difficulties"].append(int(row["difficulty"]))

    # Validate
    errors = []
    for pn, cats in puzzles.items():
        if len(cats) != 4:
            errors.append(f"Puzzle {pn}: expected 4 categories, got {len(cats)}")
        for cat, data in cats.items():
            if len(data["words"]) != 4:
                errors.append(f"Puzzle {pn} / '{cat}': expected 4 words, got {len(data['words'])}")
    if errors:
        for e in errors:
            print("ERROR:", e, file=sys.stderr)
        sys.exit(1)

    out = [HEADER]
    out.append("final List<Puzzle> allPuzzles = [")

    for pn, cats in puzzles.items():
        out.append(f"  Puzzle(")
        out.append(f"    number: {pn},")
        out.append(f"    categories: [")

        for slot_idx, (cat_name, data) in enumerate(cats.items()):
            slot = COLOR_SLOTS[slot_idx % len(COLOR_SLOTS)]
            # Average difficulty rounded -> overall category difficulty
            avg_diff = round(sum(data["difficulties"]) / len(data["difficulties"]))
            words_dart = ", ".join(f"'{esc(w)}'" for w in data["words"])

            out.append("      Category(")
            out.append(f"        name: '{esc(cat_name)}',")
            out.append(f"        hint: '{esc(data['hint'])}',")
            out.append(f"        words: [{words_dart}],")
            out.append(f"        color: {slot['color']},")
            out.append(f"        textColor: {slot['textColor']},")
            out.append(f"        borderColor: {slot['borderColor']},")
            out.append(f"        emoji: '{slot['emoji']}',")
            out.append(f"        difficulty: {avg_diff},")
            out.append("      ),")

        out.append("    ],")
        out.append("  ),")

    out.append("];")
    out.append(FOOTER)

    result = "\n".join(out)

    if out_path:
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(result)
        print(f"Wrote {out_path} — {len(puzzles)} puzzles", file=sys.stderr)
    else:
        print(result)


if __name__ == "__main__":
    main()
